// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-menu-items.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_menu_items_default = defineTool({
  name: "list_menu_items",
  title: "List menu items",
  description: "List images and videos configured in the digital menu board slideshow.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("menu_items").select("*").order("order_index", { ascending: true }).limit(limit ?? 50);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-audio-tracks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_audio_tracks_default = defineTool2({
  name: "list_audio_tracks",
  title: "List music tracks",
  description: "List background music tracks used by the slideshow audio player.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("audio_tracks").select("*").limit(limit ?? 50);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_announcements_default = defineTool3({
  name: "list_announcements",
  title: "List voice announcements",
  description: "List voice-over announcement audio clips played between music tracks on the slideshow.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("announcements").select("*").limit(limit ?? 50);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-slideshow-settings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_slideshow_settings_default = defineTool4({
  name: "get_slideshow_settings",
  title: "Get slideshow settings",
  description: "Read the current slideshow configuration (theme, intervals, custom message, etc).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("slideshow_settings").select("*").limit(1).maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { settings: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hqetuukelgurerlfnmqd";
var mcp_default = defineMcp({
  name: "menu-board-mcp",
  title: "Menu Board Digital",
  version: "0.1.0",
  instructions: "Read-only tools for the Menu Board Digital app: list slideshow media (images/videos), music tracks, voice announcements, and current slideshow settings. Calls act as the signed-in Menu Board user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_menu_items_default,
    list_audio_tracks_default,
    list_announcements_default,
    get_slideshow_settings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
